main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Docs
    url: /docs/
    weight: 3
  - name: Vintage
    url: '#vintage'
    weight: 4
  - name: Experience
    url: '#experience'
    weight: 5
